/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerEstoque;
import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelEstoque;
import model.ModelProduto;
import util.Mascaras;

/**
 *
 * @author CaroleCristhian
 */
public class ViewEstoque extends javax.swing.JFrame {

    ArrayList<ModelEstoque> listaModelEstoque = new ArrayList<>();
    ControllerEstoque controllerEstoque = new ControllerEstoque();
    ModelEstoque modelEstoque = new ModelEstoque();
    Mascaras formatado = new Mascaras();
    
    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    
    
    String salvarAlterar;
    /**
     * Creates new form Estoque
     */
    public ViewEstoque() {
        initComponents();
        carregaestoque();
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfProduto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEstoque = new javax.swing.JTable();
        jbSalvar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jtfQtdMi = new javax.swing.JFormattedTextField();
        jtfQtdMa = new javax.swing.JFormattedTextField();
        jtfQtdAt = new javax.swing.JFormattedTextField();
        jtfDescProduto = new javax.swing.JTextField();
        jbPesqProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque");

        jLabel1.setText("Código");

        jtfCodigo.setEditable(false);

        jLabel2.setText("Produto");

        jLabel3.setText("Qtd. Minima");

        jLabel4.setText("Qtd. Maxima");

        jLabel5.setText("Qtd. Atual");

        jtfProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfProdutoFocusLost(evt);
            }
        });
        jtfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfProdutoKeyPressed(evt);
            }
        });

        jtEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Produto", "Qtd. Minima", "Qtd. Maxima", "Qtd. Atual"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtEstoque);
        if (jtEstoque.getColumnModel().getColumnCount() > 0) {
            jtEstoque.getColumnModel().getColumn(0).setMinWidth(50);
            jtEstoque.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtEstoque.getColumnModel().getColumn(0).setMaxWidth(50);
            jtEstoque.getColumnModel().getColumn(2).setMinWidth(75);
            jtEstoque.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtEstoque.getColumnModel().getColumn(2).setMaxWidth(75);
            jtEstoque.getColumnModel().getColumn(3).setMinWidth(75);
            jtEstoque.getColumnModel().getColumn(3).setPreferredWidth(75);
            jtEstoque.getColumnModel().getColumn(3).setMaxWidth(75);
            jtEstoque.getColumnModel().getColumn(4).setMinWidth(75);
            jtEstoque.getColumnModel().getColumn(4).setPreferredWidth(75);
            jtEstoque.getColumnModel().getColumn(4).setMaxWidth(75);
        }

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_save_2561379.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\CaroleCristhian\\Documents\\NetBeansProjects\\Restaurante\\src\\imagens\\imagens\\if_new-24_103173.png")); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_new10_216291.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_cancel_216128.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_cross-24_103181.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Pesquisar");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\CaroleCristhian\\Documents\\NetBeansProjects\\Restaurante\\src\\imagens\\imagens\\if_70_111121.png")); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jtfQtdMi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtfQtdMa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtfQtdAt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtfDescProduto.setEditable(false);

        jbPesqProduto.setText("...");
        jbPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfCodigo)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtfQtdMi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDescProduto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfQtdMa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jtfQtdAt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(jbNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jbAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSalvar)
                                .addGap(28, 28, 28)
                                .addComponent(jbExcluir)))
                        .addGap(0, 85, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPesqProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfQtdMi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfQtdMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfQtdAt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbNovo)
                    .addComponent(jbAlterar)
                    .addComponent(jbSalvar)
                    .addComponent(jbExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if(validaCampos()==false){
            return;
        }
        if(salvarAlterar.equals("salvar")){
          this.salvar();  
        }else{
          this.alterar();    
        }
           
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        //EXCLUI NO BANCO
        int linha = jtEstoque.getSelectedRow();
        int codigo = (int) jtEstoque.getValueAt(linha, 0);
        
        if(controllerEstoque.excluirEstoqueController(codigo)){
            JOptionPane.showMessageDialog(this, "Estoque Excluido com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaestoque();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir o estoque","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(true);
        this.limparCampos();
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        this.habilitarDesabilitarCampos(true);
        
        int linha = this.jtEstoque.getSelectedRow();
        try{
            int codigo = (int) this.jtEstoque.getValueAt(linha, 0);
            
            //recupera dados do banco
            modelEstoque = controllerEstoque.getEstoqueController(codigo);
            //seta nos campos
            this.jtfCodigo.setText(String.valueOf(modelEstoque.getId_estoque()));
            this.jtfProduto.setText(String.valueOf(modelEstoque.getProduto_estoque()));
            this.jtfDescProduto.setText(modelEstoque.getDescricao_produto());
            this.jtfQtdAt.setText(String.valueOf(modelEstoque.getQtdatual_estoque()));
            this.jtfQtdMa.setText(String.valueOf(modelEstoque.getQtdemaxima_estoque()));
            this.jtfQtdMi.setText(String.valueOf(modelEstoque.getQtdeminima_estoque()));
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Erro ou não encontrado", "Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jtEstoque.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtEstoque.setRowSorter(classificador);
        String texto = jtfPesquisa.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqProdutoActionPerformed
        // TODO add your handling code here:
        if(jtfProduto.getText().isEmpty()){
            ViewPesqProduto JFPesquisa = new ViewPesqProduto();
            JFPesquisa.origemPesquisa = "Estoque";
            JFPesquisa.setLocationRelativeTo(null);
            JFPesquisa.setVisible(true);
            JFPesquisa.setResizable(false);
            JFPesquisa.FPrincipalEstoque(this);
            
        }
    }//GEN-LAST:event_jbPesqProdutoActionPerformed

    private void jtfProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdutoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfProdutoKeyPressed

    private void jtfProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfProdutoFocusLost

       if(jtfProduto.getText().isEmpty()==false){
            //recupera dados do banco
            modelProduto = controllerProduto.getProdutoController(Integer.parseInt(jtfProduto.getText()));
            jtfDescProduto.setText(modelProduto.getDescricao_produto());
            if(jtfDescProduto.getText().isEmpty()){
               jtfProduto.setText("");
               JOptionPane.showMessageDialog(this,"Produto não encontrado!","Atenção",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jtfProdutoFocusLost

    private boolean  validaCampos(){
        boolean Situ = true;
        
        if(jtfProduto.getText().isEmpty()){
          JOptionPane.showMessageDialog(this,"Produto é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(formatado.converterVirgulaParaPontoDouble(jtfQtdAt.getText())<0){
          JOptionPane.showMessageDialog(this,"Quantidade Atual é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(formatado.converterVirgulaParaPontoDouble(jtfQtdMa.getText())<0){
          JOptionPane.showMessageDialog(this,"Quantidade Máxima é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(formatado.converterVirgulaParaPontoDouble(jtfQtdMi.getText())<0){
          JOptionPane.showMessageDialog(this,"Quantidade Mínima é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
       
        return Situ;
        
    }
    
    public void retornaPesquisaProduto(String pCodigo, String pDescricao ){
        if(! pCodigo.isEmpty()){
          jtfProduto.setText(pCodigo);
          jtfDescProduto.setText(pDescricao);    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewEstoque().setVisible(true);
            }
        });
    }
    
    private void salvar(){
        modelEstoque.setProduto_estoque(Integer.parseInt(this.jtfProduto.getText()));
        modelEstoque.setQtdatual_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdAt.getText()));
        modelEstoque.setQtdemaxima_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdMa.getText()));
        modelEstoque.setQtdeminima_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdMi.getText()));
        
        if(controllerEstoque.salvarEstoqueController(modelEstoque) > 0){
            JOptionPane.showMessageDialog(this,"Estoque cadastrado com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaestoque();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
            
        } else{
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar estoque!","Erro",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void alterar(){
        modelEstoque.setProduto_estoque(Integer.parseInt(this.jtfProduto.getText()));
        modelEstoque.setQtdatual_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdAt.getText()));
        modelEstoque.setQtdemaxima_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdMa.getText()));
        modelEstoque.setQtdeminima_estoque(formatado.converterVirgulaParaPontoDouble(this.jtfQtdMi.getText()));
        
        if(controllerEstoque.atualizarEstoqueController(modelEstoque)){
            JOptionPane.showMessageDialog(this,"Estoque altarado com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaestoque();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
            
        } else{
            JOptionPane.showMessageDialog(this,"Erro ao alterar estoque!","Erro",JOptionPane.ERROR_MESSAGE);
        } 
    }
            
    private void limparCampos(){
        jtfCodigo.setText("");
        jtfProduto.setText("");
        jtfDescProduto.setText("");
        jtfQtdAt.setText("0,00");
        jtfQtdMa.setText("0,00");
        jtfQtdMi.setText("0,00");   
    }
    
    private void habilitarDesabilitarCampos(boolean situacao){
        jtfProduto.setEditable(situacao);
        jbPesqProduto.setEnabled(situacao);
        jtfQtdAt.setEditable(situacao);
        jtfQtdMa.setEditable(situacao);
        jtfQtdMi.setEditable(situacao);
    }
    
     private void carregaestoque(){
        listaModelEstoque = controllerEstoque.getListaEstoqueController();
        DefaultTableModel modelo = (DefaultTableModel) jtEstoque.getModel();
        modelo.setNumRows(0);
        
        //inserir produtos na tabela
        int cont = listaModelEstoque.size();
        for (int i = 0; i < cont; i++){
            modelo.addRow(new Object[]{
            listaModelEstoque.get(i).getId_estoque(),
            listaModelEstoque.get(i).getDescricao_produto(),
            listaModelEstoque.get(i).getQtdeminima_estoque(),
            listaModelEstoque.get(i).getQtdemaxima_estoque(),            
            listaModelEstoque.get(i).getQtdatual_estoque()
            });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesqProduto;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTable jtEstoque;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescProduto;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JFormattedTextField jtfQtdAt;
    private javax.swing.JFormattedTextField jtfQtdMa;
    private javax.swing.JFormattedTextField jtfQtdMi;
    // End of variables declaration//GEN-END:variables
}
