/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerFornecedor;
import controller.ControllerProduto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelFornecedor;
import model.ModelProduto;
import util.Mascaras;

/**
 *
 * @author CaroleCristhian
 */
public class ViewProduto extends javax.swing.JFrame {
    
    ArrayList<ModelProduto> listaModelProduto = new ArrayList<>();
    ControllerProduto controllerProduto = new ControllerProduto();
    ModelProduto modelProduto = new ModelProduto();
    Mascaras formatado = new Mascaras();
    
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    
    String salvarAlterar;
    

    /**
     * Creates new form Produto
     */
    public ViewProduto() {
        initComponents();
        carregaprodutos();
        setLocationRelativeTo(null);
        habilitarDesabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfDescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfFornecedor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtfPesquisa = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jtfPreco = new javax.swing.JFormattedTextField();
        jtfUnidade = new javax.swing.JFormattedTextField();
        jtfDescFornecedor = new javax.swing.JTextField();
        jbPesqFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produto");

        jLabel1.setText("Código");

        jtfCodigo.setEditable(false);

        jLabel2.setText("Descrição");

        jLabel3.setText("Unidade");

        jLabel4.setText("Preço");

        jLabel5.setText("Fornecedor");

        jtfFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfFornecedorFocusLost(evt);
            }
        });
        jtfFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFornecedorActionPerformed(evt);
            }
        });

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Descrição", "Unidade", "Preço", "Fornecedor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtProduto);
        if (jtProduto.getColumnModel().getColumnCount() > 0) {
            jtProduto.getColumnModel().getColumn(0).setMinWidth(50);
            jtProduto.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtProduto.getColumnModel().getColumn(0).setMaxWidth(50);
            jtProduto.getColumnModel().getColumn(2).setMinWidth(75);
            jtProduto.getColumnModel().getColumn(2).setPreferredWidth(75);
            jtProduto.getColumnModel().getColumn(2).setMaxWidth(75);
            jtProduto.getColumnModel().getColumn(3).setMinWidth(75);
            jtProduto.getColumnModel().getColumn(3).setPreferredWidth(75);
            jtProduto.getColumnModel().getColumn(3).setMaxWidth(75);
            jtProduto.getColumnModel().getColumn(4).setMinWidth(100);
            jtProduto.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtProduto.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_cancel_216128.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_new10_216291.png"))); // NOI18N
        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_new-24_103173.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_save_2561379.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesquisar");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_70_111121.png"))); // NOI18N
        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_cross-24_103181.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jtfUnidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        jtfDescFornecedor.setEditable(false);

        jbPesqFornecedor.setText("...");
        jbPesqFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jtfUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtfFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPesqFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDescFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jtfDescricao))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbExcluir)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfDescFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPesqFornecedor))
                    .addComponent(jtfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbNovo)
                    .addComponent(jbAlterar)
                    .addComponent(jbSalvar)
                    .addComponent(jbExcluir))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        if(validaCampos()==false){
            return;
        }
        
        if(salvarAlterar.equals("salvar")){
          this.salvar();  
        }else{
          this.alterar();    
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        // TODO add your handling code here:
        //EXCLUI NO BANCO
        int linha = jtProduto.getSelectedRow();
        int codigo = (int) jtProduto.getValueAt(linha, 0);
        
        if(controllerProduto.excluirProdutoController(codigo)){
            JOptionPane.showMessageDialog(this, "Produto Excluido com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaprodutos();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao excluir o produto","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(true);
        this.limparCampos();
        
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.habilitarDesabilitarCampos(false);
        this.limparCampos();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        this.habilitarDesabilitarCampos(true);
        
        int linha = this.jtProduto.getSelectedRow();
        try{
            int codigo = (int) this.jtProduto.getValueAt(linha, 0);
            
            //recupera dados do banco
            modelProduto = controllerProduto.getProdutoController(codigo);
            //seta nos campos
            this.jtfCodigo.setText(String.valueOf(modelProduto.getId_produto()));
            this.jtfDescricao.setText(modelProduto.getDescricao_produto());
            this.jtfFornecedor.setText(String.valueOf(modelProduto.getFornecedor_produto()));
            this.jtfPreco.setText(String.valueOf(modelProduto.getPreco_produto()));
            this.jtfUnidade.setText(modelProduto.getUnidade_produto());
            this.jtfDescFornecedor.setText(modelProduto.getNome_fornecedor());
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"Erro ou não encontrado", "Aviso",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) this.jtProduto.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtProduto.setRowSorter(classificador);
        String texto = jtfPesquisa.getText();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbPesqFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqFornecedorActionPerformed
        // TODO add your handling code here:
        if(jtfFornecedor.getText().isEmpty()){
            ViewPesqFornecedor JFPesquisa = new ViewPesqFornecedor();
            JFPesquisa.origemPesquisa = "Estoque";
            JFPesquisa.setLocationRelativeTo(null);
            JFPesquisa.setVisible(true);
            JFPesquisa.setResizable(false);
            JFPesquisa.FPrincipal(this);

        }
    }//GEN-LAST:event_jbPesqFornecedorActionPerformed

    private void jtfFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFornecedorFocusLost
        if(jtfFornecedor.getText().isEmpty()==false){
            //recupera dados do banco
            modelFornecedor = controllerFornecedor.getFornecedorController(Integer.parseInt(jtfFornecedor.getText()));
            jtfDescFornecedor.setText(modelFornecedor.getNome_fornecedor());
            if(jtfDescFornecedor.getText().isEmpty()){
               jtfFornecedor.setText("");
               JOptionPane.showMessageDialog(this,"Fornecedor não encontrado!","Atenção",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jtfFornecedorFocusLost

    private void jtfFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFornecedorActionPerformed

    
    public void retornaPesquisaFornecedor(String pCodigo, String pDescricao ){
        if(! pCodigo.isEmpty()){
          jtfFornecedor.setText(pCodigo);
          jtfDescFornecedor.setText(pDescricao);    
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }
    
    private void salvar(){
        modelProduto.setDescricao_produto(this.jtfDescricao.getText());
        modelProduto.setFornecedor_produto(Integer.parseInt(this.jtfFornecedor.getText()));
        modelProduto.setUnidade_produto(this.jtfUnidade.getText());
        modelProduto.setPreco_produto(formatado.converterVirgulaParaPontoDouble(this.jtfPreco.getText()));
        
        if(controllerProduto.salvarProdutoController(modelProduto) > 0){
            JOptionPane.showMessageDialog(this,"Produto cadastrado com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaprodutos();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
            
        } else{
            JOptionPane.showMessageDialog(this,"Erro ao cadastrar produto!","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void alterar(){
        modelProduto.setDescricao_produto(this.jtfDescricao.getText());
        modelProduto.setFornecedor_produto(Integer.parseInt(this.jtfFornecedor.getText()));
        modelProduto.setUnidade_produto(this.jtfUnidade.getText());
        modelProduto.setPreco_produto(formatado.converterVirgulaParaPontoDouble(this.jtfPreco.getText()));
        
        if(controllerProduto.atualizarProdutoController(modelProduto)){
            JOptionPane.showMessageDialog(this,"Produto altarado com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
            this.carregaprodutos();
            this.limparCampos();
            this.habilitarDesabilitarCampos(false);
            
        } else{
            JOptionPane.showMessageDialog(this,"Erro ao alterar produto!","Erro",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean  validaCampos(){
        boolean Situ = true;
        
        if(jtfFornecedor.getText().isEmpty()){
          JOptionPane.showMessageDialog(this,"Fornecedor é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(formatado.converterVirgulaParaPontoDouble(jtfPreco.getText())<0){
          JOptionPane.showMessageDialog(this,"Preço é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(jtfUnidade.getText().isEmpty()){
          JOptionPane.showMessageDialog(this,"Unidade é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
        if(jtfDescricao.getText().isEmpty()){
          JOptionPane.showMessageDialog(this,"Descrição é obrigatório","Atenção",JOptionPane.WARNING_MESSAGE);
          Situ = false;
        }
       
        return Situ;
        
    }
    
    private void limparCampos(){
        jtfCodigo.setText("");
        jtfDescricao.setText("");
        jtfDescFornecedor.setText("");
        jtfFornecedor.setText("");
        jtfPreco.setText("0,00");
        jtfUnidade.setText("");    
    }
    
    private void habilitarDesabilitarCampos(boolean situacao){
        jtfDescricao.setEditable(situacao);
        jtfFornecedor.setEditable(situacao);
        jbPesqFornecedor.setEnabled(situacao);
        jtfPreco.setEditable(situacao);
        jtfUnidade.setEditable(situacao);
    }
    
    private void carregaprodutos(){
        listaModelProduto = controllerProduto.getListaProdutoController();
        DefaultTableModel modelo = (DefaultTableModel) jtProduto.getModel();
        modelo.setNumRows(0);
        
        //inserir produtos na tabela
        int cont = listaModelProduto.size();
        for (int i = 0; i < cont; i++){
            modelo.addRow(new Object[]{
            listaModelProduto.get(i).getId_produto(),
            listaModelProduto.get(i).getDescricao_produto(),
            listaModelProduto.get(i).getUnidade_produto(),
            listaModelProduto.get(i).getPreco_produto(),
            listaModelProduto.get(i).getNome_fornecedor()
            
            });
    }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesqFornecedor;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDescFornecedor;
    private javax.swing.JTextField jtfDescricao;
    private javax.swing.JTextField jtfFornecedor;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JFormattedTextField jtfPreco;
    private javax.swing.JFormattedTextField jtfUnidade;
    // End of variables declaration//GEN-END:variables
}
