/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerComanda;
import controller.ControllerComandaCliente;
import controller.ControllerComandaitem;
import controller.ControllerEstoque;
import controller.ControllerProduto;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelComanda;
import model.ModelComandaCliente;
import model.ModelComandaitem;
import model.ModelEstoque;
import model.ModelProduto;
import util.BLDatas;
import controller.ControllerEstoqueComandaItemEstoque;
import model.ModelEstoqueComandaItemEstoque;
import  java.util.ArrayList;
import model.ModelComanda;

/**
 *
 * @author CaroleCristhian
 */
public class ViewComanda extends javax.swing.JFrame {
    
    ControllerEstoque controllerEstoque = new ControllerEstoque();
    ModelEstoque modelEstoque = new ModelEstoque();
    ArrayList<ModelEstoque> listaModelEstoque = new ArrayList<>();
    
    ArrayList<ModelComandaCliente> listaModelComandaCliente = new ArrayList<>();
    ControllerComandaCliente controllerComandaCliente = new ControllerComandaCliente();
    ControllerComanda cotrollerComanda = new ControllerComanda();
    ModelComanda modelComanda = new ModelComanda();
    
    BLDatas bLDatas = new BLDatas();
    ControllerComandaitem controllerComandaitem = new ControllerComandaitem();
    ModelComandaitem modelComandaitem = new ModelComandaitem();
    ArrayList<ModelComandaitem> listaModelComandaitem = new ArrayList<>();
    
    ControllerEstoqueComandaItemEstoque controllerEstoqueComandaItemEstoque = new ControllerEstoqueComandaItemEstoque();
    ModelEstoqueComandaItemEstoque modelEstoqueComandaItemEstoque = new ModelEstoqueComandaItemEstoque();
    ModelComanda modelComanda1 = new ModelComanda();
    ArrayList<ModelEstoqueComandaItemEstoque> listamodelComandaItemEstoques = new ArrayList<>();
    
    String alterarSalvar;
    
    
    int item = 0;
    
    

    /**
     * Creates new form ViewComanda
     */
    public ViewComanda() {
        
        initComponents();
        setLocationRelativeTo(null);
        carregaComanda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jcbPesquisa = new javax.swing.JComboBox<>();
        jtfPesquisa = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtComanda = new javax.swing.JTable();
        jbAlterar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtfProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbPesqProduto = new javax.swing.JButton();
        jtfDescProduto = new javax.swing.JTextField();
        jtfCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jbPesqProduto1 = new javax.swing.JButton();
        jtfDescCliente = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfQuantidade = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jbIncluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComandaItem = new javax.swing.JTable();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jftLiquido = new javax.swing.JFormattedTextField();
        jftDesconto = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfDisponivel = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jftTotal = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jbNovo = new javax.swing.JButton();
        jtfUnitario = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("Opção de Pesquisa");

        jcbPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição", "Unidade", "Preço", "Fornecedor" }));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_70_111121.png"))); // NOI18N
        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jtComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Comanda", "Cliente", "Data", "Bruto", "Desconto", "Liquido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtComanda);

        jbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_button_ok_685.png"))); // NOI18N
        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens/if_cancel_216128.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcbPesquisa, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExcluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAlterar)
                    .addComponent(jbExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPanel2);

        jtfProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfProdutoFocusLost(evt);
            }
        });
        jtfProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfProdutoKeyPressed(evt);
            }
        });

        jLabel2.setText("Produto/Estoque");

        jbPesqProduto.setText("...");
        jbPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqProdutoActionPerformed(evt);
            }
        });

        jtfDescProduto.setEditable(false);

        jtfCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfClienteFocusLost(evt);
            }
        });
        jtfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfClienteKeyPressed(evt);
            }
        });

        jLabel3.setText("Cliente");

        jbPesqProduto1.setText("...");
        jbPesqProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesqProduto1ActionPerformed(evt);
            }
        });

        jtfDescCliente.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Comanda");

        jtfQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfQuantidade.setText("0");
        jtfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfQuantidadeFocusLost(evt);
            }
        });

        jLabel4.setText("Quantidade");

        jbIncluir.setText("Incluir");
        jbIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIncluirActionPerformed(evt);
            }
        });

        jtComandaItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód.Produto", "Produto", "QTDE", "Vlr.Unitario", "Vlr.Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtComandaItem);
        if (jtComandaItem.getColumnModel().getColumnCount() > 0) {
            jtComandaItem.getColumnModel().getColumn(0).setMinWidth(75);
            jtComandaItem.getColumnModel().getColumn(0).setPreferredWidth(75);
            jtComandaItem.getColumnModel().getColumn(0).setMaxWidth(75);
            jtComandaItem.getColumnModel().getColumn(1).setMinWidth(200);
            jtComandaItem.getColumnModel().getColumn(1).setPreferredWidth(200);
            jtComandaItem.getColumnModel().getColumn(1).setMaxWidth(200);
            jtComandaItem.getColumnModel().getColumn(2).setMinWidth(50);
            jtComandaItem.getColumnModel().getColumn(2).setPreferredWidth(50);
            jtComandaItem.getColumnModel().getColumn(2).setMaxWidth(50);
            jtComandaItem.getColumnModel().getColumn(3).setMinWidth(85);
            jtComandaItem.getColumnModel().getColumn(3).setPreferredWidth(85);
            jtComandaItem.getColumnModel().getColumn(3).setMaxWidth(85);
            jtComandaItem.getColumnModel().getColumn(4).setMinWidth(85);
            jtComandaItem.getColumnModel().getColumn(4).setPreferredWidth(85);
            jtComandaItem.getColumnModel().getColumn(4).setMaxWidth(85);
        }

        jbCancelar.setText("Cancelar");

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jftLiquido.setText("0");

        jftDesconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jftDesconto.setText("0");
        jftDesconto.setToolTipText("");
        jftDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftDescontoFocusLost(evt);
            }
        });

        jLabel6.setText("Desconto");

        jLabel7.setText("Liquido");

        jtfDisponivel.setEditable(false);
        jtfDisponivel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfDisponivel.setText("0,00");
        jtfDisponivel.setEnabled(false);

        jLabel5.setText("Disponivel");

        jftTotal.setEditable(false);
        jftTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,#0"))));
        jftTotal.setText("0,00");
        jftTotal.setEnabled(false);

        jLabel9.setText("Vlr. Total");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jtfUnitario.setEditable(false);
        jtfUnitario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        jtfUnitario.setText("0,00");
        jtfUnitario.setEnabled(false);

        jLabel10.setText("Vlr.Unitario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbPesqProduto1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDescCliente))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jtfProduto)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtfUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jftTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbIncluir)))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jftLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfDescCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPesqProduto1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbPesqProduto)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jbIncluir)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jftTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtfUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCancelar)
                            .addComponent(jbSalvar)
                            .addComponent(jftDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jftLiquido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNovo))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastro", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void aplicarDesconto(){
        jftLiquido.setText(String.valueOf(Double.parseDouble(jftLiquido.getText())-Double.parseDouble(jftDesconto.getText())));
    }
    private void jbPesqProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqProduto1ActionPerformed
        // TODO add your handling code here:
        if(jtfCliente.getText().isEmpty()){
            ViewPesqCliente JFPesquisa = new ViewPesqCliente();
            JFPesquisa.setLocationRelativeTo(null);
            JFPesquisa.setVisible(true);
            JFPesquisa.setResizable(false);
            JFPesquisa.FPrincipal(this);

        }
    }//GEN-LAST:event_jbPesqProduto1ActionPerformed

    private void jtfClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfClienteKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClienteKeyPressed

    private void jtfClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfClienteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfClienteFocusLost

    private void jbPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesqProdutoActionPerformed
        // TODO add your handling code here:
        if(jtfProduto.getText().isEmpty()){
            ViewPesqEstoque JFPesquisa = new ViewPesqEstoque();
            JFPesquisa.setLocationRelativeTo(null);
            JFPesquisa.setVisible(true);
            JFPesquisa.setResizable(false);
            JFPesquisa.FPrincipal(this);

        }
    }//GEN-LAST:event_jbPesqProdutoActionPerformed

    private void jtfProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfProdutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProdutoKeyPressed

    private void jtfProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfProdutoFocusLost

        if(jtfProduto.getText().isEmpty()==false){
            //recupera dados do banco
            modelEstoque = controllerEstoque.getEstoqueController(Integer.parseInt(jtfProduto.getText()));
            jtfDescProduto.setText(modelEstoque.getDescricao_produto());
            jtfDisponivel.setText(String.valueOf(modelEstoque.getQtdatual_estoque()));
            if(jtfDescProduto.getText().isEmpty()){
                jtfProduto.setText("");
                JOptionPane.showMessageDialog(this,"Produto não encontrado no estoque!","Atenção",JOptionPane.WARNING_MESSAGE);
            }

        }
    }//GEN-LAST:event_jtfProdutoFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        alterarSalvar="Alterar";
        int linha = jtComanda.getSelectedRow();
        int CodigoVenda = (int) jtComanda.getValueAt(linha, 0);
        listamodelComandaItemEstoques = controllerEstoqueComandaItemEstoque.getListaEstoqueComandaItemController(CodigoVenda);
        DefaultTableModel modelo =(DefaultTableModel) jtComandaItem.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listamodelComandaItemEstoques.size(); i++) {
            listamodelComandaItemEstoques.get(i).getModelEstoque().getId_estoque();
            listamodelComandaItemEstoques.get(i).getModelEstoque().getDescricao_produto();
            listamodelComandaItemEstoques.get(i).getModelComandaitem().getQdte_comandaitem();
           
            
        }

    }//GEN-LAST:event_jbAlterarActionPerformed

    public void somarValorTota(){
        double soma = 0, valor;
        int cont = jtComandaItem.getRowCount();
        for (int i=0; i < cont; i++){
            valor = (double) jtComandaItem.getValueAt(i, 4);
            soma = soma + valor;
        }
        jftLiquido.setText(String.valueOf(soma));
        aplicarDesconto();
    }
    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
       int linha = jtComanda.getSelectedRow();
       int codigoVenda =  (int) jtComanda.getValueAt(linha, 0);
       listamodelComandaItemEstoques =new ArrayList<>();
       listamodelComandaItemEstoques = controllerEstoqueComandaItemEstoque.getListaEstoqueComandaItemController(codigoVenda);
       for(int i= 0; i <listamodelComandaItemEstoques.size();i++){
           modelEstoque = new ModelEstoque();
           modelEstoque.setId_estoque(listamodelComandaItemEstoques.get(i).getModelEstoque().getId_estoque());
           //modelEstoque.setDescricao_produto(listamodelComandaItemEstoques).get(i)getModelEstoque.getdescricao_produto();
       }
       if(cotrollerComanda.excluirComandaController(codigoVenda)){
           JOptionPane.showMessageDialog(this,"Comanda excluida com sucesso!","Atenção",JOptionPane.WARNING_MESSAGE);
           this.carregaComanda();
       }else{
           JOptionPane.showMessageDialog(this,"Erro ao excluir comanda!","Atenção",JOptionPane.ERROR_MESSAGE);
       }
       
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIncluirActionPerformed
        // TODO add your handling code here:
        if((jtfQuantidade.getText().equals(""))||(jtfQuantidade.getText().equals("0,00"))){
            JOptionPane.showMessageDialog(this,"Quantidade invalida!","Atenção",JOptionPane.WARNING_MESSAGE);
        }else{
            modelEstoque = controllerEstoque.getEstoqueController(Integer.parseInt(jtfProduto.getText()));
            
            DefaultTableModel modelo = (DefaultTableModel) jtComandaItem.getModel();
            int cont = 0;
            //double quantidade = 0;
            //quantidade = Double.parseDouble(jtfQuantidade.getText());
            for(int i = 0; i < cont; i++){
                modelo.setNumRows(0);;   
            }
            
            modelo.addRow(new Object[]{
              //  item = item +1,
                Integer.parseInt(jtfProduto.getText()),
                modelEstoque.getDescricao_produto(),
                Double.parseDouble(jtfQuantidade.getText()),
                Double.parseDouble(jtfUnitario.getText()),
                Double.parseDouble(jftTotal.getText())
                  
            });
            
            somarValorTota();
        }
    }//GEN-LAST:event_jbIncluirActionPerformed

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        // TODO add your handling code here:
        alterarSalvar = "Salvar";
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfQuantidadeFocusLost
        // TODO add your handling code here:
        jftTotal.setText(String.valueOf(Double.parseDouble(jtfQuantidade.getText())*Double.parseDouble(jtfUnitario.getText())));
    }//GEN-LAST:event_jtfQuantidadeFocusLost

    private void jftDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftDescontoFocusLost
        // TODO add your handling code here:
       somarValorTota();;
    }//GEN-LAST:event_jftDescontoFocusLost

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed

        int codigoComanda=0, quantidade, codigoProduto = 0;
        listaModelComandaitem = new ArrayList<>();
        listaModelComandaitem = new ArrayList<>();
        
        modelComanda.setCliente_comanda(Integer.parseInt(jtfCliente.getText()));
        try {
            modelComanda.setData_comanda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(ViewComanda.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelComanda.setBruto_comanda(Double.parseDouble(jftLiquido.getText())+Double.parseDouble(jftDesconto.getText()));
        modelComanda.setDesconto_comanda(Double.parseDouble(jftDesconto.getText()));
        modelComanda.setLiquido_comanda(Double.parseDouble(jftLiquido.getText()));
        
        codigoComanda = cotrollerComanda.salvarComandaController(modelComanda);
        if(codigoComanda>0){
            JOptionPane.showMessageDialog(this, "Comanda salva!","Atenção",JOptionPane.WARNING_MESSAGE);
            carregaComanda();
        }else{
            JOptionPane.showMessageDialog(this, "Erro Comanda!","Atenção",JOptionPane.ERROR_MESSAGE);
        }
        
        int cont = jtComandaItem.getRowCount();
        int item = 0;
        for(int i = 0; i < cont; i++){
            item = item + 1;
            modelComandaitem = new ModelComandaitem();
            modelEstoque = new ModelEstoque();
            modelComandaitem.setId_comandaitem(codigoComanda);
            modelComandaitem.setId_produto((int) jtComandaItem.getValueAt(i, 0));
            modelComandaitem.setItem_comandaitem(item);
            modelComandaitem.setQdte_comandaitem((Double) jtComandaItem.getValueAt(i, 2));
            modelComandaitem.setValortotal_comandaitem((Double) jtComandaItem.getValueAt(i, 4));
            modelEstoque.setId_estoque((int) jtComandaItem.getValueAt(i, 0));
           
            modelEstoque.setQtdatual_estoque((Double) jtComandaItem.getValueAt(i, 2));
            
            listaModelComandaitem.add(modelComandaitem);
            listaModelEstoque.add(modelEstoque);
            
        }
        if(controllerComandaitem.salvarComandaitemController(listaModelComandaitem)){
            controllerEstoque.atualizarDisponivelEstoqueController(listaModelEstoque);
        JOptionPane.showMessageDialog(this, "Item da comanda salva!","Atenção",JOptionPane.WARNING_MESSAGE);
            carregaComanda();
        }else{
            JOptionPane.showMessageDialog(this, "Erro no item da comanda!","Atenção",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    public void retornaPesquisa(String pCodigo, String pDescricao, Double pQTDDisponivel, Double pUnitario){
        if(! pCodigo.isEmpty()){
          jtfProduto.setText(pCodigo);
          jtfDescProduto.setText(pDescricao);    
          jtfDisponivel.setText(String.valueOf(pQTDDisponivel));
          jtfUnitario.setText(String.valueOf(pQTDDisponivel));
        }
    }
    
    public void retornaPesquisaCliente(String pCodigo, String pDescricao){
        if(! pCodigo.isEmpty()){
          jtfCliente.setText(pCodigo);
          jtfDescCliente.setText(pDescricao);    
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewComanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewComanda().setVisible(true);
            }
        });
    }
    
     private void carregaComanda(){
        listaModelComandaCliente = controllerComandaCliente.getListaComandaClienteController();
        DefaultTableModel modelo = (DefaultTableModel) jtComanda.getModel();
         modelo.setNumRows(0);
        
        //inserir produtos na tabela
        int cont = listaModelComandaCliente.size();
        for (int i = 0; i < cont; i++){
            modelo.addRow(new Object[]{
            listaModelComandaCliente.get(i).getModelComanda().getId_comanda(),
            listaModelComandaCliente.get(i).getModelCliente().getNome_cliente(),
            listaModelComandaCliente.get(i).getModelComanda().getData_comanda(),
            listaModelComandaCliente.get(i).getModelComanda().getBruto_comanda(),            
            listaModelComandaCliente.get(i).getModelComanda().getDesconto_comanda(),
            listaModelComandaCliente.get(i).getModelComanda().getLiquido_comanda()
            });
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbIncluir;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesqProduto;
    private javax.swing.JButton jbPesqProduto1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbPesquisa;
    private javax.swing.JFormattedTextField jftDesconto;
    private javax.swing.JFormattedTextField jftLiquido;
    private javax.swing.JFormattedTextField jftTotal;
    private javax.swing.JTable jtComanda;
    private javax.swing.JTable jtComandaItem;
    private javax.swing.JTextField jtfCliente;
    private javax.swing.JTextField jtfDescCliente;
    private javax.swing.JTextField jtfDescProduto;
    private javax.swing.JFormattedTextField jtfDisponivel;
    private javax.swing.JTextField jtfPesquisa;
    private javax.swing.JTextField jtfProduto;
    private javax.swing.JFormattedTextField jtfQuantidade;
    private javax.swing.JFormattedTextField jtfUnitario;
    // End of variables declaration//GEN-END:variables
}
